services:
  db:
    image: postgres:18
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/18/data
    restart: unless-stopped
    ports:
      - 5432:5432

volumes:
  postgres_data:
